"""房间持久化存储（ADR-0001 §2.1、§2.2）的公开入口。"""

from storage.store import (
    APP_NAME,
    DEFAULT_SESSION_NAME,
    DEFAULT_READ_LIMIT,
    MAX_READ_LIMIT,
    MAX_RECORD_BYTES,
    MAX_SESSION_NAME_CHARS,
    MAX_TEXT_BYTES,
    ROOM_DIR_MODE,
    STATE_FILE_MODE,
    STATE_SCHEMA_VERSION,
    CorruptedStorageError,
    LimitExceededError,
    RoomBusyError,
    RoomLease,
    RoomStore,
    SchemaVersionError,
    StorageError,
    TimelineRecord,
    WorkdirMismatchError,
    default_state_root,
    normalize_workdir,
    normalize_session_name,
    room_id_for,
)

__all__ = [
    "APP_NAME",
    "DEFAULT_SESSION_NAME",
    "DEFAULT_READ_LIMIT",
    "MAX_READ_LIMIT",
    "MAX_RECORD_BYTES",
    "MAX_SESSION_NAME_CHARS",
    "MAX_TEXT_BYTES",
    "ROOM_DIR_MODE",
    "STATE_FILE_MODE",
    "STATE_SCHEMA_VERSION",
    "CorruptedStorageError",
    "LimitExceededError",
    "RoomBusyError",
    "RoomLease",
    "RoomStore",
    "SchemaVersionError",
    "StorageError",
    "TimelineRecord",
    "WorkdirMismatchError",
    "default_state_root",
    "normalize_workdir",
    "normalize_session_name",
    "room_id_for",
]
